uploads = []
generated = []

[[outputs]]
id = "gNykn8_M_F4i5db5tKK2x"
uri = "file://.local/outputs/Allinma-World-------------------26.pdf"
type = "pdf"
title = "Allinma World — هاكاثون الإنماء 26 (PDF)"
